name: Zola on GitHub Pages

on: 
 push:
  branches:
   - main

jobs:
  build:
    name: Publish site
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      
    - name: Workaround bug in github actions
      run: |
        # see https://github.com/actions/runner-images/issues/6775
        git config --global --add safe.directory /github/workspace
      
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
